# Generated by Django 3.1.2 on 2020-10-22 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parse_text', '0002_document_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='theme',
            field=models.CharField(default='', max_length=60),
        ),
    ]
