# Generated by Django 3.1.2 on 2020-10-23 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parse_text', '0004_document_args'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='text_for_algo',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
