# Generated by Django 3.1.2 on 2020-11-05 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parse_text', '0005_note_text_for_algo'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='text_for_ml',
            field=models.TextField(default=''),
        ),
    ]
